### ISSUE TITLE
Improve the search button🔎  to filter Contributors names in Contribution.html file 💭

### ISSUE THREAD

**Issue by fineanmol** [fineanmol/Hacktoberfest2022#1169]
### We Have a Long List of Contributors. Adding a search button on the top will increase productivity.

**Comment by progressive-coder-ankur** [comment]
Hi there, is this issue still open ? If it is , actually i have already worked on a search bar.
![Selection_002](https://user-images.githubusercontent.com/10112468/193101129-fae59290-06bc-4939-b062-5dbaf2953ac9.png)

**Comment by fineanmol** [comment]
> We Have a Long List of Contributors

Hi Ankur, the search bar is already added. You can improve the search bar. 
like : When you backspace the text from the search filter. It shows loading.. component. Instead of it. It should show the complete list of the users.
