### ISSUE TITLE
Add front end login page

### ISSUE THREAD

**Issue by TasosY2K** [fineanmol/Hacktoberfest2022#1219]
I want to add a login page design i made with SASS and HTML
Can you assign me the issue?

**Comment by Karmpatel960** [comment]
This issue is still open or not Can i work on this?

**Comment by Ayush-Baliyan-19** [comment]
I want to work on this , please assign me this issue✨

**Comment by Harshul02** [comment]
I want to add a login page design i made with HTML and CSS.
Can you assign me the issue?

**Comment by s-k-jha** [comment]
I have created the best login page for this repository if you assign me the issue I am happy to create a pull request. This issue is still open or not Can I work on this?

**Comment by TasosY2K** [comment]
i got it guys, just make a new pr
