### ISSUE TITLE
Validate Binary Search Tree in Java

### ISSUE THREAD

**Issue by ShuYiKang** [fineanmol/Hacktoberfest2022#1333]
I'd like to contribute java code to validate binary search tree.

Validation of binary search tree includes:
- Ensuring that the value of the node in the left subtree is smaller than current node
- Ensuring that the value of the node in the right subtree is greater than current node
- Ensuring left and right subtrees are also binary search trees

**Comment by error707-persona** [comment]
Hey can you assign this one to me?

**Comment by priddhesh** [comment]
Hey can you assign me ?
