### ISSUE TITLE
Need to ask, if i can contribute my personal project

### ISSUE THREAD

**Issue by arian0zen** [fineanmol/Hacktoberfest2022#1344]
Hey, was asking can i add my person project as contribution for hacktoberfest 2022,
And one more thing on which folder do i need to add my project if I'm allowed to?
Program's_Contributed_By_Contributors
Is this the folder to add contribution for new projects?

And if I'm allowed to can you please assign me this issue, I'll PR during the hactoberfest 2022
Tjank you

**Comment by fineanmol** [comment]
> Hey, was asking can i add my person project as contribution for hacktoberfest 2022, And one more thing on which folder do i need to add my project if I'm allowed to? Program's_Contributed_By_Contributors Is this the folder to add contribution for new projects?
> 
> And if I'm allowed to can you please assign me this issue, I'll PR during the hactoberfest 2022 Tjank you

Yes, You have to contribute inside the Program's contributed by Contributors folder. 
@arian0zen  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by arian0zen** [comment]
okay okayy starred ittt.. and try to commit a PR as soon as the fest starts

**Comment by fineanmol** [comment]
> okay okayy starred ittt.. and try to commit a PR as soon as the fest starts

Sure
