### ISSUE TITLE
Add a Hactober fest pattern printing algorithm

### ISSUE THREAD

**Issue by AarizAnsari** [fineanmol/Hacktoberfest2022#1349]
I want to add a Hactober fest 2022 printing c/c++ or java  algorithm to which contributors can contribute every year by upgrading year and upgrading the style etc.

**Comment by AarizAnsari** [comment]
@fineanmol Please assign this issue to me..

**Comment by fineanmol** [comment]
@AarizAnsari  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by fineanmol** [comment]
> Hi, can you please assign it to me? I want to add a pattern printing algorithm with the help of Python.

Sure

**Comment by Dishag2611** [comment]
Hi @fineanmol 
Please assign this issue to me.

**Comment by ChaudharyRaman** [comment]
Hi @fineanmol . i would like to work on this issue. Can you assign it to me as well?

**Comment by adavadkardhruv13** [comment]
Hey @fineanmol  can you assign this to me. I also want to work on this

**Comment by SriramBharadwaj1** [comment]
Hi, could you please assign this to me. I can code in Java
