### ISSUE TITLE
Add a fingerprint scanning animation 

### ISSUE THREAD

**Issue by srinjoy-26** [fineanmol/Hacktoberfest2022#1353]
A css animation.

**Comment by srinjoy-26** [comment]
Pls assign @fineanmol

**Comment by fineanmol** [comment]
@srinjoy-26  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by srinjoy-26** [comment]
> @srinjoy-26 Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

Done
