### ISSUE TITLE
Add Python Program for Port Scanning

### ISSUE THREAD

**Issue by smit-sms** [fineanmol/Hacktoberfest2022#1354]
Adding a CLI python script/program for scanning ports that are available on the provided URL or host IP address.

**Comment by smit-sms** [comment]
@fineanmol Please assign this to me as a part of hacktoberfest and with the hacktoberfest-accepted label as well.

**Comment by fineanmol** [comment]
@smit-sms  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by smit-sms** [comment]
@fineanmol Done. Thanks.
