### ISSUE TITLE
Load more button

### ISSUE THREAD

**Issue by progressive-coder-ankur** [fineanmol/Hacktoberfest2022#1361]
As the list of contributors is ever growing, the page gets quiet long. May be loading few contributors on page load e.g 36 or 48, and loading another 48 on demand with a load more button.

**Comment by fineanmol** [comment]
> As the list of contributors is ever growing, the page gets quiet long. May be loading few contributors on page load e.g 36 or 48, and loading another 48 on demand with a load more button.

That's a nice optimization. We can build that too.

**Comment by fineanmol** [comment]
> As the list of contributors is ever growing, the page gets quiet long. May be loading few contributors on page load e.g 36 or 48, and loading another 48 on demand with a load more button.

After Implementing Load more button, A bug is introduced. 
It's a static website, so after the load more button, It is not re rendering the component. It is adding the same users until your count crossed the total contribution list. And then it is showing the total users on page.
