### ISSUE TITLE
Add Personal Project

### ISSUE THREAD

**Issue by gkumar-pandey** [fineanmol/Hacktoberfest2022#1363]
Hii @fineanmol 
i want to add my react project to this repo so please assign to me

**Comment by fineanmol** [comment]
@gkumar-pandey  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by gkumar-pandey** [comment]
Done

**Comment by ChaudharyRaman** [comment]
Hii @fineanmol . I would like to add my project to this repo . can you please assign it to me?

**Comment by ArnabC27** [comment]
Hii @fineanmol! Can you please assign this task to me so that I can I add my project to this repo?

**Comment by chetansingh-2** [comment]
Hii @fineanmol can u please assign this task to me?

**Comment by s-k-jha** [comment]
hello, sir can you assign this to me I want to add my latest project based on the landing page to this repository. can you provide a "hacktober-accepted" label for the event? @fineanmol

**Comment by rathi710** [comment]
hello @fineanmol i would like add my personal project, can you please assign it to me.

**Comment by vedant-z** [comment]
@fineanmol I also want to add my project

**Comment by KumarUtsav1025** [comment]
hello, @fineanmol sir, I want to add my personal project of amazon UI clone using flutter.

**Comment by Harish2930** [comment]
Hi @fineanmol sir, I want to add my personal project of Facebook Login Page Clone using TailwindCSS 
Please assign me the task

**Comment by KumarUtsav1025** [comment]
@fineanmol Please review my pull request

**Comment by stoody-dev** [comment]
hi @fineanmol I want to add my personal project of javascript digital clock . Please assign me this task
