### ISSUE TITLE
Add a JavaScript Black-Jack game 

### ISSUE THREAD

**Issue by Rajpreetkaur02** [fineanmol/Hacktoberfest2022#1366]
Hey!
I want to add a black-Jack game created using HTML, CSS, and JS under the folder Programs_contributed_by_contributers/JavaScript_programs.

Please assign it to me.

**Comment by fineanmol** [comment]
@Rajpreetkaur02  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by Rajpreetkaur02** [comment]
Done.

**Comment by IayushCoderJOD** [comment]
I love to create crazy project every weekend and I want  to add my own GYM's website  to earn "hacktober-accepted"  label for the event.

**Comment by fineanmol** [comment]
> I love to create crazy project every weekend and I want to add my own GYM's website to earn "hacktober-accepted" label for the event.

Sure,

**Comment by IayushCoderJOD** [comment]
plz assign this to me.

**Comment by fineanmol** [comment]
@IayushCoderJOD  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by IayushCoderJOD** [comment]
done sir

**Comment by Rajpreetkaur02** [comment]
I have already created a PR for the same, kindly see to it.
#1384

**Comment by fineanmol** [comment]
> I have already created a PR for the same, kindly see to it. #1384

There are conflicts in your PR

**Comment by Rajpreetkaur02** [comment]
> > I have already created a PR for the same, kindly see to it. #1384
> 
> There are conflicts in your PR

yes, I am trying to solve it.

**Comment by Rajpreetkaur02** [comment]
I have resolved the conflict. Please check now #1384
