### ISSUE TITLE
Add new React Project

### ISSUE THREAD

**Issue by anudeeps0306** [fineanmol/Hacktoberfest2022#1370]
I would like to create a new folder to submit react js folder, and submit a todo website .

**Comment by fineanmol** [comment]
> I would like to create a new folder to submit react js folder, and submit a todo website .

Sure, @anudeeps0306  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by anudeeps0306** [comment]
can you please add label to this issue

**Comment by 17Moons** [comment]
I would also like to contribute in the project

**Comment by fineanmol** [comment]
> I would also like to contribute in the project

Sure
