### ISSUE TITLE
Add a new hangman game in Java 

### ISSUE THREAD

**Issue by pragyaSingh13** [fineanmol/Hacktoberfest2022#1386]
Hey I want to contribute my personal hangman game for hacktober 2022. Thanks.

**Comment by computerwala** [comment]
HI @fineanmol I would like to contribute to this issue please assign this to me 
thanks in advance..!!
Happy Hacking !!

**Comment by fineanmol** [comment]
> HI @fineanmol I would like to contribute to this issue please assign this to me thanks in advance..!! Happy Hacking !!

@pragyaSingh13  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.
