### ISSUE TITLE
Adding A New Tile Game using python

### ISSUE THREAD

**Issue by IAmLittleCoder** [fineanmol/Hacktoberfest2022#1438]
Hey @fineanmol, I would like to contribute to this. Please assign this to me.
I have forked and have star the repo.
Thanks in Advance...!!

**Comment by IAmLittleCoder** [comment]
Can I get Hactoberfest-accepted Label

**Comment by fineanmol** [comment]
@IAmLittleCoder  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by IAmLittleCoder** [comment]
@fineanmol Done
