### ISSUE TITLE
Minimum Size Subarray Sum

### ISSUE THREAD

**Issue by tomriddle77** [fineanmol/Hacktoberfest2022#1464]
pr #1463  please take a look  and accept it so that I can make my first contibution

Given an array of positive integers nums and a positive integer target, return the minimal length of a contiguous subarray [numsl, numsl+1, ..., numsr-1, numsr] of which the sum is greater than or equal to target. If there is no such subarray, return 0 instead.

**Comment by tomriddle77** [comment]
please assign me this issue

**Comment by Rohans-7** [comment]
Please assign this issue to me. I will add the solution in two approches.
