### ISSUE TITLE
Want to add sieve method for prime nos. in cpp. Can I go ahead

### ISSUE THREAD

**Issue by raj-hero** [fineanmol/Hacktoberfest2022#1504]
I want to add sieve method for prime nos. in cpp. Can I go ahead? Moreover, apart from doing a pull request of my code, what else will I have to do?
Also, will I have to add my name in contributers.html list?

**Comment by sanketdisale871** [comment]
I want to add the sieve method for finding prime numbers and calculating the prime factors of a number.  Can you assign it? @fineanmol

**Comment by raj-hero** [comment]
> I want to add the sieve method for finding prime numbers and calculating the prime factors of a number. Can you assign it? @fineanmol

I've already committed the code
