### ISSUE TITLE
Adding a react-based text-utility

### ISSUE THREAD

**Issue by MR-DHRUV** [fineanmol/Hacktoberfest2022#1533]
hey @fineanmol 
I want to add a react based text utility which can do the following operations on the given piece of text
- Remove extra spaces
- Parse text from html
- convert to lower / upper case
- style the best (italics / bold)
- Count characters and words

**Comment by fineanmol** [comment]
@MR-DHRUV  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by MR-DHRUV** [comment]
@fineanmol Already did

**Comment by MR-DHRUV** [comment]
@fineanmol I wanted to ask if I have to update contributors.html with my profile card or not

**Comment by fineanmol** [comment]
> anted to ask if I have to update contributors.html with my profile card or not and please look into this

Issue has been resolved. You can create a new PR now.
