### ISSUE TITLE
Guess The Number! Game 

### ISSUE THREAD

**Issue by vishal1patidar** [fineanmol/Hacktoberfest2022#1554]
I would like to contribute to Guess The Number using HTML, CSS and JS! Game,  After win rewards also show. Please assign this issue to me @fineanmol

**Comment by fineanmol** [comment]
@vishal1patidar  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by vishal1patidar** [comment]
Done ✅

**Comment by ppap1771** [comment]
hey i would like to work on this. Can you assign me this issue please.

**Comment by ppap1771** [comment]
hey i made the game with a GUI can i still create a pull request ??? @fineanmol
