### ISSUE TITLE
Adding My Codeforces Contest Solutions in C++.

### ISSUE THREAD

**Issue by goodchai0** [fineanmol/Hacktoberfest2022#1563]
I would like to contribute  My Codeforces Contest Solutions in C++ ! Please assign this issue to me @fineanmol  Under hacktoberfest 2022

**Comment by fineanmol** [comment]
> I would like to contribute My Codeforces Contest Solutions in C++ ! Please assign this issue to me @fineanmol Under hacktoberfest 2022

Sure

**Comment by fineanmol** [comment]
@goodchai0  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by goodchai0** [comment]
Done. I have Star the repo

**Comment by JohnnyQuintero16** [comment]
Hi, send solutions
