### ISSUE TITLE
Reading a JSON file and returning a String response using Java.

### ISSUE THREAD

**Issue by codeX1616** [fineanmol/Hacktoberfest2022#1573]
Hello @fineanmol, please assign me this issue to create a simple JSON file reader and String response extractor.

**Comment by fineanmol** [comment]
@codeX1616  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by codeX1616** [comment]
Hi @fineanmol I am unable to push my changes to the repository. This is the message I get when trying to push my changes - Permission to fineanmol/Hacktoberfest2022.git denied to codeX1616.

**Comment by codeX1616** [comment]
Its resolved now, had been using the wrong ssh key. Have raised the PR now. Please review and merge.
