### ISSUE TITLE
Want to add palindrome linkedlist program in java.

### ISSUE THREAD

**Issue by d-coder111** [fineanmol/Hacktoberfest2022#1587]

**Comment by ronakpanchalk9** [comment]
Hey @fineanmol I'd like to add this program

**Comment by fineanmol** [comment]
> Hey @fineanmol I'd like to add this program

Sure

**Comment by fineanmol** [comment]
@ronakpanchalk9  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.
