### ISSUE TITLE
Adding solution to N-Queens problem

### ISSUE THREAD

**Issue by VaibhavArora314** [fineanmol/Hacktoberfest2022#1588]
hey @fineanmol  , I want to add my solution to the N-Queens problem in cpp.

**Comment by fineanmol** [comment]
> hey @fineanmol , I want to add my solution to the N-Queens problem in cpp.

Sure

**Comment by fineanmol** [comment]
@VaibhavArora314  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

Already done
