### ISSUE TITLE
Binary Search in a sorted cyclic array

### ISSUE THREAD

**Issue by YBansal95** [fineanmol/Hacktoberfest2022#1592]
I would like to contribute the code for binary search in a sorted cyclic array. Please assign this issue to me @fineanmol under hacktoberfest 2022

**Comment by fineanmol** [comment]
> I would like to contribute the code for binary search in a sorted cyclic array. Please assign this issue to me @fineanmol under hacktoberfest 2022

Sure

**Comment by fineanmol** [comment]
@YBansal95  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by vishwasgowdahv** [comment]
Assign this to me I’ll do it

**Comment by CarefoDragneel** [comment]
Assign this issue to me and I will send PR immediately as I have already written the code for this program
