### ISSUE TITLE
Some popular recursion problems

### ISSUE THREAD

**Issue by PravarAnu** [fineanmol/Hacktoberfest2022#1618]
I would like to contribute some popular recursion problems solution in C++ ! Please assign this issue to me @fineanmol under hacktoberfest 2022 and help me in starting my first contribution.

**Comment by fineanmol** [comment]
@PravarAnu  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by Anushree1291** [comment]
I would like to contribute some popular recursion problems solution as well as Backtracking. I can code in Java as well as in Kotlin. Please assign this issue to me @fineanmol under hacktoberfest 2022.
