### ISSUE TITLE
Python Program To Display Calendar

### ISSUE THREAD

**Issue by UkaniVedant** [fineanmol/Hacktoberfest2022#1681]
Want to add a basic python code that display calendar for the month and year given by the user.
Please assign this issue to me @fineanmol under hacktoberfest 2022 and help me in starting my first contribution. I have already Starred ⭐ the repo.

**Comment by Akankshaaaa29** [comment]
I want to work on this issue, please assign me @fineanmol under hacktoberfest2022. I've already forked and starred
 this repo.

**Comment by RoopakMallik** [comment]
@fineanmol  Please assign me this issue to resolve or provide me another issue to work on based on Python.

**Comment by RoopakMallik** [comment]
Can you please let me know why the repo has the excluded tag on the
hacktober website
