### ISSUE TITLE
Want to add a motivational quotes chrome Extension 

### ISSUE THREAD

**Issue by shubhrastogi07** [fineanmol/Hacktoberfest2022#1688]
Hey @fineanmol, 
Want to add a chrome extension which shows a new motivational quote every time it is clicked using a public API.
Please assign this issue to me under hacktoberfest 2022 and help me in starting my first contribution. I have already starred the repo and forked it.

**Comment by shubhrastogi07** [comment]
@fineanmol I have made a pull request for the same kindly review it and merge it.

**Comment by pr0x7** [comment]
@fineanmol i'd like to take this ,plz assign me 🙏🏻
