### ISSUE TITLE
Rock Paper Scissors

### ISSUE THREAD

**Issue by satvikDesktop** [fineanmol/Hacktoberfest2022#1695]
Want to add a rock paper scissors game website @fineanmol

**Comment by fineanmol** [comment]
> Want to add a rock paper scissors game website @fineanmol

Sure

**Comment by fineanmol** [comment]
@satvikDesktop  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by mprsAbhinavShri** [comment]
respected sir @fineanmol please assign this project to me

**Comment by SKSilentKiller** [comment]
@fineanmol I want to contribute to this project

**Comment by Laxmankohar** [comment]
Hey @fineanmol, please assign me this issue under Hacktoberfest 2022. I want to contribute on this.

**Comment by mprsAbhinavShri** [comment]
respected sir @fineanmol please tell me the language i can code it in
