### ISSUE TITLE
Vigenere Code solver using python

### ISSUE THREAD

**Issue by AnsahMohammad** [fineanmol/Hacktoberfest2022#1701]
I would like to add an algorithm for **Vigenere code** encryption-decryption using Python. Assign to me under HacktoberFest2022

**Comment by deveshparmar** [comment]
Hello,  I would like to contribute towards this issue

**Comment by AnsahMohammad** [comment]
@deveshparmar I have already made the project ready, maybe you could do other projects .
Thanks.
