### ISSUE TITLE
Number guessing game using python

### ISSUE THREAD

**Issue by rohansrivastava5491** [fineanmol/Hacktoberfest2022#1711]
This project is a fun game that generates a random number in a certain specified range and the user must guess the number after receiving hints. Every time a user’s guess is wrong they are prompted with more hints to make it easier — at the cost of reducing the score.

**Comment by rohansrivastava5491** [comment]
I want to work on this. Please assign this issue to me @rohansrivastava5491 under hacktoberfest 2022 so that I can start contributing.

**Comment by SahilSatyam** [comment]
I have worked on similar project, please assign this to me.

**Comment by disuja7** [comment]
I want to work on it. Please provide the full details for the project.

**Comment by ankur0904** [comment]
I want to work on it. Please assigned this to me.
