### ISSUE TITLE
Alarm Clock program using python

### ISSUE THREAD

**Issue by rohansrivastava5491** [fineanmol/Hacktoberfest2022#1738]
It is a Command Line Interface (CLI) Python application. It is more than just setting off an alarm, this program allows certain YouTube links to be added to a text file. When a user sets an alarm, the code picks a random video and starts playing it.

Can you assign this issue to me?

**Comment by shrutiso05** [comment]
Hi @fineanmol can you assign me for this issue . I know how to solve. To solving this issue we import some packages like datetime, time, sounds and  tkinter package too so I request you to please assign me this project .

**Comment by fineanmol** [comment]
@rohansrivastava5491 @shrutiso05  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by shrutiso05** [comment]
I just request new pull request of updated alarm_clock program. I request you to please see My PR
