### ISSUE TITLE
Adding my Leetcode solutions

### ISSUE THREAD

**Issue by vishnup2002** [fineanmol/Hacktoberfest2022#1740]
I would like to contribute solutions of the Leetcode problems that I have solved in C++.  Please assign this issue to me @fineanmol under hacktoberfest 2022.

**Comment by vishwasgowdahv** [comment]
I had done 200+ questions done on competitive coding platforms, I could do this work very efficiently, so please assign this work to me.

**Comment by Sandyy07** [comment]
I have solutions to Amazon OA . Please Assign me this issue

**Comment by CarefoDragneel** [comment]
I have done 280+ problems on leetcode and I have a collection of solutions for many standard, frequently asked problems. Please assign this issue to me.
