### ISSUE TITLE
C# Folder 

### ISSUE THREAD

**Issue by SarthakSharma660** [fineanmol/Hacktoberfest2022#1748]
Can I Add a C# Folder and Linked List code to it?

**Comment by SarthakSharma660** [comment]
@fineanmol i have not made apr to your repo and still you marked my issue closed , may I know the reason why?

**Comment by fineanmol** [comment]
@SarthakSharma660 please create your PR for the event. You don't need an issue attached with it.

**Comment by SarthakSharma660** [comment]
@fineanmol okay 👍🏻
