### ISSUE TITLE
Rock-paper-scissors and lizards game using Python

### ISSUE THREAD

**Issue by Shreya241** [fineanmol/Hacktoberfest2022#1786]
I will write code for a 4 player game. Rock-paper and scissors are very common and can be played between between 3, but this game can be played between 4.
Please assign this issue to me @fineanmol.

**Comment by Hackingwithshaurya** [comment]
i will do it! @fineanmol

**Comment by Shreya241** [comment]
@fineanmol can u assign this under hacktoberfest please
