### ISSUE TITLE
wanto to style the footer 

### ISSUE THREAD

**Issue by swastik-bose007** [fineanmol/Hacktoberfest2022#1829]

**Comment by Dulyaaa** [comment]
can you assign this to me @swastik-bose007

**Comment by palaksv** [comment]
Please assign this issue to me.

**Comment by Sandyy07** [comment]
Please assign me this issue

**Comment by Codebraker7** [comment]
I'd like to work on this issue! Please assign this to me

**Comment by Vrajjangid5** [comment]
please assign this task to me

**Comment by kushagrarastogi7007** [comment]
pls assign this to  me @fineanmol

**Comment by fineanmol** [comment]
@kushagrarastogi7007 @Vrajjangid5  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by Dulyaaa** [comment]
Done in #2076. Please check @fineanmol and let me know the modifications.
