### ISSUE TITLE
Animated-Profile-Card

### ISSUE THREAD

**Issue by Tara-Choudhary** [fineanmol/Hacktoberfest2022#1845]
I want to add Animated-Profile-Card using CSS. 
@fineanmol  Please assign me this issue under hacktoberfest 2022

**Comment by alphaCoderR** [comment]
Can i work on it??

**Comment by AdarshPradhan1508** [comment]
HEY THERE @fineanmol , PLEASE ASSIGN THIS ISSUE TO ME FOR HACKTOBERFEST2022

**Comment by Dev-tanay** [comment]
Can i work on it??
