### ISSUE TITLE
Pig Game using Javascript

### ISSUE THREAD

**Issue by Jatayu-u** [fineanmol/Hacktoberfest2022#1896]
Hello, @fineanmol I would like to add a Pig game project, which is a fun dice game using HTML, CSS, and javascript.
 please assign me this issue under Hacktoberfest 2022.
I have already starred ⭐️ the repo.

**Comment by Aditi192002** [comment]
Please assign this to me . I have already starred it.

**Comment by SKSilentKiller** [comment]
Hey Can you please assign this task to me @fineanmol

**Comment by harshalwaghare18** [comment]
I can develope this game using JavaScript. Can you please assign it to me ?
