### ISSUE TITLE
In frontend projects, to-do-list project, Add an element on pressing Enter 

### ISSUE THREAD

**Issue by KedarKK1** [fineanmol/Hacktoberfest2022#1900]
In frontend projects, to-do-list project, Add an element on pressing Enter  along with clicking on Add button for ease of user

**Comment by Codebraker7** [comment]
Hey! I'd like to contribute to this project

**Comment by raikiran07** [comment]
hello everyone, I have already work on projects similar to this issue, it would be great if at any means I can help on this project, can anyone assign me this task so that I can start my work. @KedarKK1 can you please assign me this task along with hacktoberfest tag?
