### ISSUE TITLE
Number Guesser Game using javascript Html and CSS

### ISSUE THREAD

**Issue by headshigh** [fineanmol/Hacktoberfest2022#1903]

**Comment by bhadurajbala22** [comment]
I wanted to build this Number Guesser Game using JavaScript Html and CSS. Please assign me this issue.

**Comment by headshigh** [comment]
No

**Comment by raikiran07** [comment]
@headshigh can you please assign me this task as I have already build one of this game just a week ago using the same technologies you have mentioned in the issue, it would be great if you assign me this task with the hacktoberfest tag.
