### ISSUE TITLE
A login card on web

### ISSUE THREAD

**Issue by amanmodiii** [fineanmol/Hacktoberfest2022#1928]
Hey @fineanmol ,
I would like to create a single-page demo signup page.
Please assign me the task .
Regards.

**Comment by amanmodiii** [comment]
I have already starred the repository.

**Comment by abhishekkashyap96** [comment]
@amanmodiii are you working on this ? If not,  @fineanmol , Please assign me.

**Comment by amanmodiii** [comment]
I have submitted the code files and created a pull request

**Comment by Aditi192002** [comment]
Please assign it to me
