### ISSUE TITLE
Dice Roll Simulator

### ISSUE THREAD

**Issue by UkaniVedant** [fineanmol/Hacktoberfest2022#1946]
Hello, @fineanmol I would like to add a Dice Roll Simulator using Python.
please assign me this issue under Hacktoberfest 2022.
I have already starred ⭐️ the repo.

**Comment by kushagrarastogi7007** [comment]
I would like to add a dice  roll simulator game (like) in this , can you pls assign this project to me @fineanmol

**Comment by nilesh05apr** [comment]
Hello @fineanmol and fellow developers I have added a Unicode Dice Roll Simulator using Tkinter and have created a pull request, please review the changes.
