### ISSUE TITLE
Hang Man using Python

### ISSUE THREAD

**Issue by arinjain373** [fineanmol/Hacktoberfest2022#1955]
I would like to add hang man game in your repository, under Hacktoberfest2022. Can you please assign it to me. @fineanmol

**Comment by Aditi192002** [comment]
Please assign it to me , I would like to add it to your repository

**Comment by fineanmol** [comment]
@Aditi192002 @arinjain373  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by arinjain373** [comment]
@fineanmol Done

**Comment by Aditi192002** [comment]
@fineanmol starred
