### ISSUE TITLE
add favicon 

### ISSUE THREAD

**Issue by NageshMandal** [fineanmol/Hacktoberfest2022#1956]

**Comment by kalyanjyoti11** [comment]
hi, would love to work on this issue. please, assign me this.

**Comment by Aditi192002** [comment]
I would be really grateful if you assign this project to me. I have already starred it

**Comment by Codebraker7** [comment]
Hey! I'd like to take up this issue!

**Comment by omgoyal22** [comment]
hey i would like to take up this issue please assign it to me

**Comment by devUT27** [comment]
Please assign me this task

**Comment by Pixel-101** [comment]
Hey, I would like to take up this issue and solve it efficiently. Thanks

**Comment by chhavitekriwal** [comment]
Hey, I would like to work on this! Could you assign me this issue please?

**Comment by aadarshmani** [comment]
Hi, I would like to work on this issue. Please assign it to me. Thanks.

**Comment by SuddhasilC** [comment]
Hey, I would like to work on this issue! Could you please assign it to me.

**Comment by Nayanika-12** [comment]
Hi @fineanmol please assign me this issue, I can fix it.

**Comment by 22shubh22** [comment]
seems resolved @NageshMandal

**Comment by 1Alisha** [comment]
Please assign this work to me
