### ISSUE TITLE
Forming A Color With The Help Of Red, Green And Blue

### ISSUE THREAD

**Issue by code08-ind** [fineanmol/Hacktoberfest2022#1969]
A web application Forming A Color With The Help Of Red, Green And Blue By Scrolling The Performance Bar And Doing It In The Form A Web Application.

**Comment by bhuvan-tech** [comment]
Hi @code08-ind , I can help you with that, can you please assign me with this issue under Hacktoberfest 2022.

**Comment by code08-ind** [comment]
I have started this issue and the maintainer will assign it too me. You are requested to start with new issue.
