### ISSUE TITLE
Number Guessing game in python

### ISSUE THREAD

**Issue by HellspawnXerxes** [fineanmol/Hacktoberfest2022#1970]
Can you assign me this task? I will be really grateful if you tag this as my Hacktoberfest 2022 contribution.

**Comment by shivam779823** [comment]
Could  you please assgin me this task. this would be my first contribution to hacktoberfest

**Comment by raikiran07** [comment]
Hello everyone, I have already made this game using html, css and javascript. I also build one using react so I have the capability to help others using these technologies, it would be great if anyone could assign me this task with hacktoberfest tag so that I can start my opensource journey.
