### ISSUE TITLE
important dsa questions asked in faang/maang!

### ISSUE THREAD

**Issue by tusharrao198** [fineanmol/Hacktoberfest2022#1976]
Would like to add some important dsa questions asked in faang.
Please mark this as hacktoberfest accepted issue.

**Comment by tejasjaiswal07** [comment]
Sounds interesting to me @tusharrao198, please assign me to this issue. 
Thank you!

**Comment by tejasjaiswal07** [comment]
@tusharrao198 Would it be ok to include love babber DSA questions with their solutions?

**Comment by AbhiIkhar** [comment]
I am newb to open source  , @tusharrao198  Can u please  assign me  this issue.

**Comment by Himanshi2511** [comment]
i am keenly intrested in this @tusharrao198 ,please assign me to this issue
