### ISSUE TITLE
create a dice-based race game on browser 

### ISSUE THREAD

**Issue by amanmodiii** [fineanmol/Hacktoberfest2022#1997]
I have a JS project (front-end) that implements concepts to create a roll race game.
Link : https://amanmodiii.github.io/Roll-Race/

Hey @fineanmol ,
Please assign this task to me under hacktober-accepted.
Thanks.

**Comment by fineanmol** [comment]
@amanmodiii  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.
