### ISSUE TITLE
Remove redundant files from CSS/JS folder 😯

### ISSUE THREAD

**Issue by fineanmol** [fineanmol/Hacktoberfest2022#2]
---
name: Custom issue template
about: Describe this issue template's purpose here.

---

**Comment by shubhraagarwal** [comment]
Hey @fineanmol, I would like to work on this issue please assign it to me. Also, please add hacktoberfest label to the issue

**Comment by fineanmol** [comment]
@shubhraagarwal Please do your contribution and make a pull request

**Comment by Devrajsinh-Jhala** [comment]
Hello Sir @fineanmol Can you please assign this to me.
I really want to conribute

**Comment by fineanmol** [comment]
> Hello Sir @fineanmol Can you please assign this to me. I really want to conribute

Please go Ahead and make a pull request.

**Comment by Devrajsinh-Jhala** [comment]
Can anyone please guide me how to remove such redundant files? and how to spot them in first place

**Comment by ArihantJain123** [comment]
Hello Would you assign this issue to me ?

**Comment by fineanmol** [comment]
> Hello Would you assign this issue to me ?

Please make your pull request

**Comment by nikhiljhawar** [comment]
Hi Anmol,
Could you please help me how would I contribute to hacktoberfest2021 as I am new to it.
