### ISSUE TITLE
Added Dijkastra solution 

### ISSUE THREAD

**Issue by Abhishek-5854** [fineanmol/Hacktoberfest2022#2019]

**Comment by Danish-Belal** [comment]
@fineanmol  assign this to me

**Comment by fineanmol** [comment]
@Danish-Belal @Abhishek-5854  Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.

**Comment by Danish-Belal** [comment]
@fineanmol  give me hactoberfest tag

**Comment by Abhishek-5854** [comment]
give me hacktoberfest tag  i have star this repo
