### ISSUE TITLE
 Quiz Game using HTML and JAVASCRIPT

### ISSUE THREAD

**Issue by Rabeet8** [fineanmol/Hacktoberfest2022#2176]
Hello, @fineanmol I would like to add a 'Quiz Game' using HTML and JAVASCRIPT
Kindly assign me this issue under Hacktoberfest 2022.
I have already starred ⭐️ the repo.

**Comment by raikiran07** [comment]
hello @fineanmol can you assign me too, I also want to contribute on this project .
