### ISSUE TITLE
Images are not loading on webpage, after the profiles are loading. Anyone can pick it up?

### ISSUE THREAD

**Issue by fineanmol** [fineanmol/Hacktoberfest2022#2213]
**Images are not loading on webpage, after the profiles are loading. It should display the user images as well in the blank avatar.** 
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/24794539/193682124-b99382f3-b5cc-4b64-a804-9f9872c5b9de.png">

### This is the expected Behaviour Reference💯 
<img width="1478" alt="image" src="https://user-images.githubusercontent.com/24794539/193682254-0fb95cce-dd10-40f4-90c8-9c3442cb5cf1.png">

**Comment by Furquan712** [comment]
Please assign it to me , I will fix it @fineanmol
