### ISSUE TITLE
Add Typing Effect Website.

### ISSUE THREAD

**Issue by Ydixit007** [fineanmol/Hacktoberfest2022#2319]
Will like to add a vanilla javascript typing effect website project.
@fineanmol Please help me to contribue to the repository.

**Comment by krishnabiradar310802** [comment]
can i work on this issue? @Ydixit007

**Comment by 1Alisha** [comment]
Please assign this work to me

**Comment by Dev-tanay** [comment]
can i work on this issue? @Ydixit007

**Comment by Ydixit007** [comment]
Hi @fineanmol , Please accept the pull request #2889 for this issue.
