### ISSUE TITLE
Solve Tower of Hanoi game using C++.

### ISSUE THREAD

**Issue by adarshgupta404** [fineanmol/Hacktoberfest2022#2372]
Please assign me this.
And make this hacktoberfest-accepted.

**Comment by Sunnyvats01** [comment]
I would like to resolve this issue. can you assign this to me

**Comment by Adeptus123** [comment]
Please assign this issue to me

**Comment by adarshgupta404** [comment]
I already done the code just have to give my PR. Waiting to get assigned.

**Comment by adarshgupta404** [comment]
Please review and merge @fineanmol

**Comment by sujalgarg17** [comment]
Please assign this issue to me

**Comment by 1Alisha** [comment]
Please assign this issue to me..

**Comment by Adeptus123** [comment]
I have made a pull request this solution kindly check and accept it

**Comment by 1Alisha** [comment]
Please review and merge my PR @fineanmol and please make this hacktoberfest-accepted.
Thanks

**Comment by SanjoySaha24** [comment]
Please assign this issue to me @fineanmol

**Comment by HarshGupta74** [comment]
@fineanmol please assign this to me.

**Comment by prasadpatil05** [comment]
hey assign me this
