### ISSUE TITLE
Kadane’s Algorithm in C++

### ISSUE THREAD

**Issue by Garvit414** [fineanmol/Hacktoberfest2022#2511]
I want to add Kadane’s Algorithm in C++ Folder .Please assign it to me @fineanmol

**Comment by nisthajnn** [comment]
please assign this to me

**Comment by PrinceSah09** [comment]
Hey , I want to Impliment  Kadane’s Algorithm please assign it to me :)

**Comment by yashvardhansingh15** [comment]
HEY, I want to assign Kadane's algorithm, please assign it to me

**Comment by PrinceSah09** [comment]
PR done :)

**Comment by Gourav1195** [comment]
I will do the task, 
Kindly assign me

**Comment by Abhishekjain113** [comment]
Please assign to me 
i am recently starting learning algorithm and open source

**Comment by vansh-patel-8123** [comment]
please assign to me

**Comment by yashvardhansingh15** [comment]
Please assign me , I could do it easily as recently alI have studied the
algorithm and solved questions on it
