### ISSUE TITLE
Longest consecutive subsequence

### ISSUE THREAD

**Issue by khareyash05** [fineanmol/Hacktoberfest2022#2670]
I would like to solve the problem of LCS using DP

**Comment by surajkeshari** [comment]
can u assign me .
i want to give c++ solution of this with full explanation through comment.

**Comment by Abhishekjain113** [comment]
Please assign to  me 
 i would like to solve

**Comment by johmn123-wq** [comment]
please assign it to me. I want to solve this using Dynamic Programming method.
