### ISSUE TITLE
NTH NUMBER IN FIBONACCI SERIES USING DP in C++

### ISSUE THREAD

**Issue by HarshGupta74** [fineanmol/Hacktoberfest2022#2760]
I would like to add Fibonacci series code in c++ using dynamic programming ans please make it hacktoberfest accepted

**Comment by rohan26062001** [comment]
Hey @HarshGupta74 I've started this work...

**Comment by raxvab** [comment]
Can I get this issue assigned  under Hacktoberfest 2022. This is the first time I'm contributing in hacktoberfest and since I've a good hold of dsa so I think i can do the job.

**Comment by SUSHREE2004** [comment]
can i solve the issue , please assign me

**Comment by ajaybara** [comment]
I want to solve the issue. This is my first contribution.

**Comment by Danish-Belal** [comment]
@fineanmol  i would like to work on it also . Kindly assign it to me.

**Comment by kondurihemant** [comment]
Hey @HarshGupta74 !!!
please assign this issue to me

**Comment by sona8340** [comment]
hey @fineanmol first time I am participating in hacktoberfest ,can you assign me this task

**Comment by ishuuuu2911** [comment]
hey @fineanmol please assign me this task,participating first  time in Hacktoberfest fest

**Comment by Chetnagupta27** [comment]
hey @fineanmol ,please assign this issue to me, participating first time in Hacktoberfest
