### ISSUE TITLE
Palindrome Checker in Javascript

### ISSUE THREAD

**Issue by psantosh16** [fineanmol/Hacktoberfest2022#3340]
I will like to make my first contribute to Hacktoberfest and I am adding Palindrome checker using JavaScript.

**Describe the solution you'd like**
Palindrome Checker will check whether user entered numbers are palindrome or not using Js concepts.

**Additional context**
This will help new Javascript learner to get started with JS Logical thinking.

I request you to assign this to me.

**Comment by psantosh16** [comment]
> @psantosh16 Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.
> Meanwhile if you want to work on this issue, Please raise the PR and we will review and merge it.


Already Stared

**Comment by psantosh16** [comment]
Created Palindrome_Checker_.js #3341 Successfully Added my first contribution in this repo , please accept my PR.

**Comment by mdzeeshan-2** [comment]
Please allow to resolve this issue

**Comment by PurtiMishra** [comment]
I would like to resolve this issue in the best possible way . Please allow me to do the same.

**Comment by nightcoder007** [comment]
hey can you assign the task to me??
