### ISSUE TITLE
Smallest Distinct Window Problem

### ISSUE THREAD

**Issue by bhavya-sharma26** [fineanmol/Hacktoberfest2022#3426]
Basically this is the problem that approaches to a commonly asked topic in technical interviews that is Sliding Window Technique.
And it would be great to include a program using this approach to this repository.

I would be code the program in C++. 

**Describe alternatives you've considered**
I could also code in java and C if you say.

Kindly assign this task to me.
It will be great step from your side

**Comment by divyanshagarwal053** [comment]
Please give me a chance to solve this issue

**Comment by Arpit-Gulgulia** [comment]
@fineanmol , can you assign this to me? I would like to take this issue for the Hacktoberfest.

**Comment by Ervin0307** [comment]
Hello @fineanmol , I would like to work on this issue, please assign this to me.

**Comment by Karthik-vangapandu8** [comment]
Hello @fineanmol, I can solve this please Assign this issue

**Comment by deepakbhagat7** [comment]
I want to work on this issue ..please assign it to me

**Comment by gaurav2612gupta** [comment]
i would like to share my solution
