### ISSUE TITLE
Fidget Spinner Game using python

### ISSUE THREAD

**Issue by Roopshali** [fineanmol/Hacktoberfest2022#3457]
Here is a working fidget spinner game.
Please assign it to me under hacktoberfest-accepted tag.

<img src= "https://user-images.githubusercontent.com/75069150/195263066-53803b3c-166b-469c-a903-05d74c40aa9f.png" width="400" height="400" />

**Comment by rakshith6404** [comment]
could u assign this to me 
i would like to work on it.....i had this same fidget spinner game as a project back in my high school

**Comment by Sritam28** [comment]
I wish to work on this project. Can u please assign me this task.

**Comment by TAnilkar** [comment]
``from turtle import *
state = {'turn': 0}
def spin():
    clear()
    angle = state['turn'] / 10
    right(angle)
    forward(100)
    dot(120, 'red')
    back(100)
    
    "second dot"
    right(120)
    forward(100)
    dot(120, 'blue')
    back(100)

    "third dot"
    right(120)
    forward(100)
    dot(120, 'green')
    back(100)
    right(120)
    update()
def animate():
    if state['turn'] > 0:
        state['turn'] -= 1
    spin()
    ontimer(animate, 20)
    
def flick():
    state['turn'] += 40 

setup(600, 400, 370, 0)
bgcolor("black")
tracer(False)
width(60)
color("orange")
onkey(flick, 'space')

listen()
animate()
done()
``
