### ISSUE TITLE
Gallery Webpage

### ISSUE THREAD

**Issue by RaginaPhalangae** [fineanmol/Hacktoberfest2022#3474]
I would like to add a Gallery webpage with beautiful styling and using components like Lightbox .Please assign me this issue .
,

**Comment by RaginaPhalangae** [comment]
> 

Started...

**Comment by RaginaPhalangae** [comment]
> @RaginaPhalangae Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event. Meanwhile if you want to work on this issue, Please raise the PR and we will review and merge it.

Started...

**Comment by AyushiGautam9** [comment]
I starred the repo...and now I hope on getting "hacktober-accepted" label for the event.

**Comment by RaginaPhalangae** [comment]
> @RaginaPhalangae Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event. Meanwhile if you want to work on this issue, Please raise the PR and we will review and merge it.

I starred the repo and now I am hoping for getting "**_hacktober-accepted_**" label for the event.

**Comment by 9520prashant** [comment]
Hello , Please Assign me this issue
