### ISSUE TITLE
Count Sort in CPP

### ISSUE THREAD

**Issue by neocollege** [fineanmol/Hacktoberfest2022#3481]
Count Sort sorting algorithm in C++ language

**Comment by neocollege** [comment]
> @neocollege Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event. Meanwhile if you want to work on this issue, Please raise the PR and we will review and merge it.

done, repo starred and PR raised

**Comment by LakshyaBhar** [comment]
Hello Sir, can you assign this issue to me

**Comment by Priyanshu-792** [comment]
I want to work on this issue ..please assign it to me

**Comment by Deepak-the-learner** [comment]
Please assign this task to me
I would like to do this in cpp and make the code understandable.

**Comment by Jam-Burger** [comment]
I would like to work on this issue.

**Comment by deepakbhagat7** [comment]
I want to work on this issue ..please assign it to me

**Comment by Sakshi2002-Sinha** [comment]
Hello, Please assign this issue to me.

**Comment by unnatigupta2019** [comment]
Hello sir , I can solve this issue please assign it to me.

**Comment by AdityaShaw1** [comment]
pls assign me this issue

**Comment by ishuuuu2911** [comment]
pls assign this issue  to  me
