### ISSUE TITLE
E-Voting system using Python

### ISSUE THREAD

**Issue by Cyber-Prajwal** [fineanmol/Hacktoberfest2022#3490]
**Is your feature request related to a problem? Please describe.**
E-Voting system / project I built using python. 

**Describe the solution you'd like**
In this python project you get to create polls, with as many options, and then allow voting for the same, the votes are stored in SQL database and after voting is ended, the winner is displayed along with piechart to show the vote distribution.
These were the python modules that I used for creating the same:
- tkinter  [The tkinter package (“Tk interface”) is the standard Python interface to the Tcl/Tk GUI toolkit]
- sqlite3 [SQLite is a C library that provides a lightweight disk-based database that doesn’t require a separate server]
- matplotlib [ matplotlib.pyplot is a collection of functions that make matplotlib work like MATLAB. Each pyplot function makes some 
                    change to a figure: e.g., creates a figure, creates  a plotting area in a figure, plots some lines in a plotting area, decorates 
                    the plot with labels, etc. ]

**Comment by Cyber-Prajwal** [comment]
Please assign this issue to me, I have starred the repo as well.

**Comment by prajak002** [comment]
sir i have starred this repo, please assign me for this issue.  i am highly obliged if you grant my request
