### ISSUE TITLE
add Celsius To Fahrenheit using javascripts

### ISSUE THREAD

**Issue by MohammadRehanPatel** [fineanmol/Hacktoberfest2022#3645]
assign me with Hacktoberfest tag

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sachinkrr02** [comment]
Hlo sir, 
Sir I have solved the issue #3645

**Comment by Bitan-Kundu** [comment]
Hello Sir, Can you assign this issue to me?

**Comment by Bitan-Kundu** [comment]
Hello sir, Can you solve this issue to me? I would like to solve this problem.

**Comment by Kankanabhowmik** [comment]
Hello sir,
Sir I have solved this issue to me? I would like to solve this problem.

**Comment by jawadkhanpk** [comment]
Hey, I can do it more accurately and my solutions would be more optimal and precise. Please assign me this issue Thanks

**Comment by jawadkhanpk** [comment]
@fineanmol
