### ISSUE TITLE
Weather App

### ISSUE THREAD

**Issue by hyprex-deva** [fineanmol/Hacktoberfest2022#3653]
I want to make the back-end of a Weather application.

It would tell the weather (temperature ,humidity, wind, precipitation etc.) of the city which a user wants to know.

**Comment by TailisUI** [comment]
I can do This. Can I work on this issue

**Comment by iamAditya01** [comment]
i have already made apps like this, do assign me this one

**Comment by SwarnitSinha** [comment]
I have experience making this kind of web app.
my repo:  https://github.com/SwarnitSinha/DecodeWeather

Assign me this task. I also starred this repository.

**Comment by Jahnavi1970** [comment]
I can work on this.

**Comment by 9520prashant** [comment]
Hello Dear, I can do your work with very optimally can you assign me this issue?
