### ISSUE TITLE
To add a tic toe game using html, jss and css

### ISSUE THREAD

**Issue by Ghat0tkach** [fineanmol/Hacktoberfest2022#3788]

**Comment by Deepanshu1008** [comment]
Can you assign this task to me?

**Comment by theshubhamgour** [comment]
Could you assign me this issue?

**Comment by 9520prashant** [comment]
Hy, I am a developer , i also know web dev. very well please assign me this project

**Comment by pratyushkr11** [comment]
Can you assign me this issue?
