### ISSUE TITLE
 Contains Duplicate

### ISSUE THREAD

**Issue by divas18** [fineanmol/Hacktoberfest2022#3827]
```
You are given an integer array nums and two integers indexDiff and valueDiff.

Find a pair of indices (i, j) such that:

i != j,
abs(i - j) <= indexDiff.
abs(nums[i] - nums[j]) <= valueDiff, and
Return true if such pair exists or false otherwise.
```
During Interview of Amdocs interviewer asked me this question

**Comment by divu02** [comment]
sir can you assign me this issue? I can solve in java/

**Comment by iamAditya01** [comment]
assign me this one

**Comment by Athrav-droid** [comment]
I'm using Java from Past 1.5 Years. I'm Pretty sure about solving this issue. I will be highly obliged if you allow me to solve the issue.

**Comment by Sritam28** [comment]
I could handle this. Could  you please assigmn this to me.
