### ISSUE TITLE
I would like to add the Heap Sort implementation in Java

### ISSUE THREAD

**Issue by ridsuteri** [fineanmol/Hacktoberfest2022#3850]
**Is your feature request related to a problem? Please describe.**
I would be adding heap sort implementation through java

**Additional context**
I would be contributing under Hacktoberfest 2022

**Comment by 9520prashant** [comment]
Please Assign me this issue!

**Comment by jawadkhanpk** [comment]
Hey Please Assign me this issue, I have a strong profile in Data Structure and Algorithms. I won lot of Hackathons in DSA. I would love to contribute to this issue. Thanks

**Comment by Sritam28** [comment]
I could work on this , could you please assign this to me

**Comment by ankit060801** [comment]
hello sir please assign me this task
