### ISSUE TITLE
I would like to make a book recommendar system using python 

### ISSUE THREAD

**Issue by gaurishajaiswal** [fineanmol/Hacktoberfest2022#3885]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gaurishajaiswal** [comment]
pull

**Comment by Kumarrupesh2310** [comment]
Please assign this issue to me.

**Comment by prajak002** [comment]
sir, could you please assign me for this

**Comment by Kumarrupesh2310** [comment]
@prajak002 you can go on with that
