### ISSUE TITLE
Navbar Social Icons

### ISSUE THREAD

**Issue by Ayushhgupta39** [fineanmol/Hacktoberfest2022#4817]
**Is your feature request related to a problem? Please describe.**
The navbar social media icons are not properly placed or aligned.

**Describe the solution you'd like**
After fixing this, the icons will look perfectly placed and more professional.

<img width="223" alt="image" src="https://user-images.githubusercontent.com/96309609/198032258-e3cf2d1a-5e38-4d7d-aa36-457747e307a8.png">

Please assign me this issue.

**Comment by Asrani-Aman** [comment]
please assign this task to me
<img width="1436" alt="Screenshot 2022-10-27 at 1 31 04 PM" src="https://user-images.githubusercontent.com/96644946/198226537-97fe37a5-6208-413d-a20f-1af41df3e3a3.png">
, I Have already resolve this issue

**Comment by Ayushhgupta39** [comment]
But the icons are still not properly aligned 
<img width="149" alt="image" src="https://user-images.githubusercontent.com/96309609/198227365-de6499d7-d080-4a4a-85e5-dad3a7886a0d.png">

**Comment by akshat2203** [comment]
hello @Ayushhgupta39 can you assign me this task..?

**Comment by MohitKumarSingh-01** [comment]
@fineanmol  this issue to me I will make sure it enhances the UI of the website as well as fulfils its function...
Thanking you in Anticipation...
Regards
Devesh Sharma

**Comment by JoshiUtsav** [comment]
**Assign this task to me **

**Comment by arnab132** [comment]
Assign to me as well.
