### ISSUE TITLE
Add math algorithms

### ISSUE THREAD

**Issue by Harsh-1309** [fineanmol/Hacktoberfest2022#948]
Hi @fineanmol! I would like to add few math algorithms to `python_programs` directory, which I would try to implement in python. Can you assign this to me?

**Comment by PreetiBaskey** [comment]
hey @Harsh-1309 , i want to add math algorithms in C++. Kindly assign me this issue.
Thank You.

**Comment by priddhesh** [comment]
Hi @fineanmol please assign me this issue.

**Comment by fineanmol** [comment]
> Hi @fineanmol please assign me this issue.

@priddhesh   Please Star ⭐️ the repo to earn "**_hacktober-accepted_**" label for the event.
