### ISSUE TITLE
Personal project - as a part of Hacktoberfest?

### ISSUE THREAD

**Issue by samyaksand** [fineanmol/Hacktoberfest2022#949]
@fineanmol Can I contribute my Spotify Clone project - as a part of Hacktoberfest?

**Comment by swatisingh46** [comment]
Please Assign this issue to me

**Comment by samyaksand** [comment]
@fineanmol Could you close this issue as hacktoberfest accepted, so that it is counted for the hacktoberfest 2021

**Comment by harsh6975** [comment]
@fineanmol I want to add NodeJs Project
Can u please assign me.

**Comment by fineanmol** [comment]
> @fineanmol I want to add NodeJs Project Can u please assign me.

Please go ahead with your request

**Comment by fineanmol** [comment]
> @fineanmol Could you close this issue as hacktoberfest accepted, so that it is counted for the hacktoberfest 2021 as Its does not show as a contribution on the hacktoberfest website even after merging

The whole project is in hacktoberfest. So you don't have to worry about it.  Just make your pull request and share the pull number

**Comment by shyam-2002** [comment]
@fineanmol I want to add a nodejs project. Could you please assign it to me.

**Comment by samyaksand** [comment]
> > @fineanmol Could you close this issue as hacktoberfest accepted, so that it is counted for the hacktoberfest 2021 as Its does not show as a contribution on the hacktoberfest website even after merging
> 
> The whole project is in hacktoberfest. So you don't have to worry about it. Just make your pull request and share the pull number

Yes, I did!
Here is the Spotify Clone PR I made - https://github.com/fineanmol/Hacktoberfest2021/pull/1011

**Comment by Memphis1983** [comment]
I've built a full stack todo-app as my personal project? Can I contribute?

**Comment by fineanmol** [comment]
> I've built a full stack todo-app as my personal project? Can I contribute?

Yes Sure

**Comment by Rakteem007** [comment]
Can I contribute to this issue @fineanmol

**Comment by fineanmol** [comment]
> Can I contribute to this issue @fineanmol

Yes

**Comment by ChaudharyRaman** [comment]
HI @fineanmol . Can i upload my project which is unsplash clone ? If yes, please assign it to me?

**Comment by stoody-dev** [comment]
can you assign this issue to me i would like to build a tribute page using html and css3
